name: Deploy Pipeline

on:
  push:
    branches: [ main ]

env:
  REGISTRY: cr.yandex
  IMAGE_NAME: clone-vk
  SERVER_IP: 37.143.10.40
  SSH_PORT: 2222
  SSH_USER: admin
  CONTAINER_PORT: 5000
  HOST_PORT: 5002

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Получение кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Настройка Yandex Cloud CLI
    - name: Configure YC CLI
      run: |
        echo "${{ secrets.YC_SA_KEY }}" > sa-key.json
        yc config set service-account-key sa-key.json
        yc config set folder-id b1gbg64nvnbues4n0i9k
        yc config set compute-default-zone ru-central1-a

    # Шаг 3: Сборка Docker-образа
    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest .

    # Шаг 4: Авторизация в Yandex Container Registry
    - name: Login to YCR
      run: |
        echo "${{ secrets.YC_SA_KEY }}" | docker login \
          --username iam \
          --password-stdin \
          ${{ env.REGISTRY }}

    # Шаг 5: Публикация образа в YCR
    - name: Push to YCR
      run: |
        docker push ${{ env.REGISTRY }}/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest

    # Шаг 6: Деплой на production-сервер
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no \
            -i <(echo "${{ secrets.SERVER_SSH_KEY }}") \
            -p ${{ env.SSH_PORT }} \
            ${{ env.SSH_USER }}@${{ env.SERVER_IP }} "
          # Обновляем образ и перезапускаем контейнер
          docker pull ${{ env.REGISTRY }}/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest && \
          docker stop ${{ env.IMAGE_NAME }} || true && \
          docker rm ${{ env.IMAGE_NAME }} || true && \
          docker run -d \
            --name ${{ env.IMAGE_NAME }} \
            --restart unless-stopped \
            -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} \
            ${{ env.REGISTRY }}/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest"