name: Test Server Connection 1

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: crpsad4gf09obkkcv8ei
  IMAGE_NAME: clone-vk
  SERVER_IP: 37.143.10.40
  SSH_PORT: 2222
  SSH_USER: admin
  CONTAINER_PORT: 5000
  HOST_PORT: 5002

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
      - name: check key
        run: |
          echo "secrets.REGISTRY_ID"
