name: Test Server Connection 1

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH key
      run: |
        # Создаем файл ключа и записываем в него содержимое секрета
        echo '${{ secrets.YC_SA_KEY }}' > key.json  # Используем одинарные кавычки!
        
        # Проверяем, что файл создан (опционально)
        ls -la key.json
        cat key.json | jq empty  # Проверка валидности JSON (если установлен jq)

    - name: Configure YC CLI
      run: yc config set service-account-key key.json
