name: Test Server Connection 1

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: crpsad4gf09obkkcv8ei
  YC_SA_KEY: '{"id":"ajen6iaj6h86qdfml928","service_account_id":"ajehm6qdf4ls3e3o67i9","created_at":"2025-07-30T17:51:45.761440888Z","key_algorithm":"RSA_2048","public_key":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpNeML8nVk35jA/iENG0\nWsUuAAHVuOwNvz99Cel+P0iwLnttlL8VAd+qUpxN03zco/JeuE4/EZKxDNCuYfb+\ntV5lbLk8/dQf86QgTAcjr6kpN99R9J2IpQYjcmaXYrYp5TxV+B891p+zrr4qruVX\nANWQqhGFT3vOVHM45dnAhjMAtygb56SVloMW1xZWh3K4nshvOC3eDcg1g73Uk7ah\nRJQ9JXjAJWdxqDqgRVB4P9siSX6mTnyIKkWwvKeaWnLUB5R1CcDkfzwDtVUtX/Gq\njV2M37rzmEPOHW8HCcYliGrQKbJRKuM5VQ7pB1Ock6JyMcI3iwNtRi3Iy1g5aGZX\nAwIDAQAB\n-----END PUBLIC KEY-----\n","private_key":"PLEASE DO NOT REMOVE THIS LINE! Yandex.Cloud SA Key ID <ajen6iaj6h86qdfml928>\n-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+k14wvydWTfmM\nD+IQ0bRaxS4AAdW47A2/P30J6X4/SLAue22UvxUB36pSnE3TfNyj8l64Tj8RkrEM\n0K5h9v61XmVsuTz91B/zpCBMByOvqSk331H0nYilBiNyZpditinlPFX4Hz3Wn7Ou\nviqu5VcA1ZCqEYVPe85Uczjl2cCGMwC3KBvnpJWWgxbXFlaHcrieyG84Ld4NyDWD\nvdSTtqFElD0leMAlZ3GoOqBFUHg/2yJJfqZOfIgqRbC8p5pactQHlHUJwOR/PAO1\nVS1f8aqNXYzfuvOYQ84dbwcJxiWIatApslEq4zlVDukHU5yTonIxwjeLA21GLcjL\nWDloZlcDAgMBAAECggEACc7x4RZlguaeelvy6aSxYJ6XYH63rj3P81DkMZdn3P/z\nuWC24hn3jdIiJQBQbRsXDAUUZO36BwCCxkMTRo18zH7gP3lFL1c0kciXtPIFHyxY\np7yBrlJRTxUCzAeFsRnpDBhP4GZTO3GawNqevcOl97AGMwqVzuJzWxtXCVVsuDte\n9aZziV3RNwJgXkA/35HPRkgecXu2/u2vUgBHpovMZW4oJF+EGYCOZStNfrT1Es8Q\n4khDkjI1wAKa2am9x8STq4PvS9GpUo7vU+dHmYfgfMiQtxAB/WXQbc+rG9e/SAHr\nsC+iB2i9Ha56DBeC4fz87rmnm2J2W0TCyNWzdLyjeQKBgQDLxxbOjrm/rRxx49BC\nRjNeMFeL8OSD+qqUSHI+xYBPZbqsvVLqgpp93XEaS26N+/WvVV0M20YDaoec++R1\nZuMErH/EpCMevStKoSMHnH5RiqYJzAmyau+rTyQSM07wlTGmknGvhzQ6ZbRvkEII\nEwMmSqE13n4N3KGWCnyPg9ls5QKBgQDvaieGll3tTRWiPww8fnHCtOtUi/YOgi1S\nUqA8kGXpV90DC/WHO67UPWoSFLczrNncMjQhHmB+W2FEFDQybCJ8PeP6Q2PaO8jI\nCvddfHNsFiR2R1LCUpvfImEMZyLM1phIxr1QRlkd3nWXGP14J65UgD6BVFLYVhvx\nXGjitM3dxwKBgQCejiVHyTPsWVTlpP3ZY2f6pKCp6WDU9EifohMKln/0x1HNsG4A\nvGhbAN9NN14pKeALcd857q92XwBv/GrRkqGXdGTh61jMRSKXKfPoqzJ6Xeg9fT4a\nTix33ddSNgv5FA0S76V3jzrrKVGQ8Oz//VMZCz6OfLUWMhKkfTpYLJ4TpQKBgQCq\nMf+pOKnK8TqI3WMYehbrAGwu7VRdGgOX+y73/vrDt/dgnBbOLQpqzMHj2qAl9yHk\n3Dect5iHGvT5TZeRpLebNPAlT9TjJg7kzo7tAXSYCOGgx7E4fTtbk3gENilSDtex\nHL8mGuxtRGC5qkU+Lo9KeOR2UfiW3Bf/K99QEpIqrwKBgEXtAJpWsME6Ere3+LNn\nl8ftqk4uM8TYId8jf5qvuTIZbSM9caO/8NdGhbAp/JXlz2MCV5y8lFz1WJx+3vMw\niOaX48E/xEJPTG1PK+EaUwBRErT53OsqNuNkI69Cl3vibTh+EF/DNGgSq1/1Rdzd\nhIc1TmANKa+kzURMIC2ZJVCA\n-----END PRIVATE KEY-----\n"}'
  IMAGE_NAME: clone-vk
  SERVER_IP: 37.143.10.40
  SSH_PORT: 2222
  SSH_USER: admin
  CONTAINER_PORT: 5000
  HOST_PORT: 5002

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
        # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          # Создаем файл ключа и записываем в него содержимое секрета
          echo '${{ secrets.YC_SA_KEY }}' > key.json  # Используем одинарные кавычки!
          
          # Проверяем, что файл создан (опционально)
          # ls -la key.json
          # cat key.json | jq empty  # Проверка валидности JSON (если установлен jq)

      - name: Install YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i
          /home/runner/yandex-cloud/bin/yc --version
          /home/runner/yandex-cloud/bin/yc config set service-account-key key.json
          /home/runner/yandex-cloud/bin/yc config set folder-id b1gbg64nvnbues4n0i9k
          /home/runner/yandex-cloud/bin/yc config set compute-default-zone ru-central1-a
          /home/runner/yandex-cloud/bin/yc config list  # Проверка настроек (опционально)

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest .

      - name: Login to YCR
        run: |
          echo "${{env.YC_SA_KEY}}" | docker login \
            --username iam \
            --password-stdin \
            ${{ env.REGISTRY }}
