name: Test Server Connection 1

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH key
      run: |
        # Создаем файл ключа и записываем в него содержимое секрета
        echo '${{ secrets.YC_SA_KEY }}' > key.json  # Используем одинарные кавычки!
        
        # Проверяем, что файл создан (опционально)
        ls -la key.json
        cat key.json | jq empty  # Проверка валидности JSON (если установлен jq)

    # - name: Configure YC CLI
    #   run: yc config set service-account-key key.json
    - name: Install YC CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i
        source /home/runner/.bashrc
        # echo 'source /home/runner/yandex-cloud/completion.zsh.inc' >>  ~/.zshrc
        yc --version
    #     curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i -b ~/yc-bin
    #     echo "~/yc-bin" >> $GITHUB_PATH
        
    # - name: Configure YC CLI
    #   run: |
    #     # Используем полный путь к yc
    #     ~/yc-bin/yc config set service-account-key key.json
    #     ~/yc-bin/yc config list
        
    #     # Проверяем доступность yc через PATH
    #     which yc || echo "yc not in PATH"
    #     yc --version || echo "Failed to run yc from PATH"
