name: Test Server Connection 1

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: crpsad4gf09obkkcv8ei
  IMAGE_NAME: clone-vk
  SERVER_IP: 37.143.10.40
  SSH_PORT: 2222
  SSH_USER: admin
  CONTAINER_PORT: 5000
  HOST_PORT: 5002

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
        # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          # Создаем файл ключа и записываем в него содержимое секрета
          echo '${{ secrets.YC_SA_KEY }}' > key.json  # Используем одинарные кавычки!
          echo '${{ secrets.YC_SA_KEY }}'
